### ISSUE TITLE
Explain significance of files

### ISSUE THREAD

**Issue by MCGallaspy** [srishtyagrawal/morango#1]
Which files do what? How do I run the simulations? Where are the results, and how should I interpret them? Might consider putting a brief explanation of the above in a readme.

**Comment by MCGallaspy** [comment]
Just have some other random observations that I'll post here as I'm poking around the code.

In `simulateNode.py` I can't seem to figure out what `Node.ALL` is supposed to do, yet it's used in a variety of places. I used this metaclass snippet to inspect the value of `Node.ALL` whenever it's called or set.

``` python
class DebugMetaclass(type):
    def __getattribute__(self, item):
        attr = object.__getattribute__(self, item)
        if item == "ALL" and attr:
            print(">>>>> ALL is " + str(attr))
        return attr

    def __setattr__(self, item, value):
        if item == "ALL":
            print(">>>>> ALL is being set to  " + str(value))
        return super(DebugMetaclass, self).__setattr__(item, value)


class Node(metaclass=DebugMetaclass):
    ALL = ""
    # More stuff following...
```

It produces no output -- the value is never changed from `""`. Therefore I suspect that all uses of it could be replaced with string literals.

**Comment by MCGallaspy** [comment]
Seems like a "record" wants some methods a bit more complex that `tuple` otherwise permits. In the simplest case, code readability might be improved by adding semantic meaning to the tuple field names using a [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple). But it also appears that you want to mutate a record's attributes, so maybe a tuple is not the appropriate choice since it's immutable?

Edit: referring to Node instance's `appData` attribute here.

**Comment by MCGallaspy** [comment]
By the way, have you heard of [Jupyter](http://jupyter.org/)? It's great for sharing simulations like this. You can write simulation code in a "notebook", run it, and cache the results and any graphs produced. Then you can share the "notebook" object with others so they can view the code and the results, and even run the code again themselves if they want.

**Comment by srishtyagrawal** [comment]
The application record data structure has been changed from tuple to a class object. The class has record ID, record data, dirty bit and partition details. The class supports functions for updating record data, clearing and setting the dirty bit among others.

A Readme with short description about files has been included.

"Node.ALL" represents the filter/partition specified along with all the records. I have not used a string literal because we are still unsure on the notation and hence I wanted my code to be flexible and adapt to any changes in notation.
